#  SITE NAME
site_name: Flask-Deta

site_description: "A Python library for seamless integration with DetaSpace in Flask"

repo_url: https://github.com/Jesparzarom/Flask-Deta
repo_name: "Flask-Deta"

# NAVIGATION
nav:
  - Home: index.md
  - Gettin Started:
      - Installation: guide/install.md
      - Configurations: guide/config.md
      - Quickstart : guide/start.md
  
  - Methods reference:
    - DetaBase: detabase/base.md
    - DetaDrive: detadrive/drive.md

  - About:
      - Changes: about/changelog.md
      - License: about/LICENSE.md

# THEME CONFIGURATIONS
theme:
  # NAME OF THEME
  name: material
  # LANGUAGE
  language: en

  # ICONS
  icon:
    repo: fontawesome/brands/github

  highlightjs: true
  hljs_style: base16-decaf
  # FONTS
  font:
    text: Fira Sans
    code: Ubuntu Mono
  # COLORS

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: pink
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4

  # FEATURES
  features:
    - navigation.footer
    - content.code.copy
    - search.highlight

# PLUGINS FOR THE SITE
plugins:
  - search

# EXTRAS
extra:
  version: 1.0.0-alpha

copyright: Copyright &copy; 2023 J.P. Esparza.

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
